### ISSUE TITLE
make readData and writeData array

### ISSUE THREAD

**Issue by nkr1729** [precice/calculix-adapter#17]
We are iterating over numReadData.

https://github.com/precice/calculix-adapter/blob/10938d846aa99e1b5a7c8a38dbf4cf5082c586aa/adapter/PreciceInterface.c#L467

But, readData is not an array.

https://github.com/precice/calculix-adapter/blob/10938d846aa99e1b5a7c8a38dbf4cf5082c586aa/adapter/PreciceInterface.h#L71

Same goes for writeData. If we have a config like this,

```
participants:

    Calculix:
        interfaces:
        - nodes-mesh: Calculix_Mesh
          patch: interface
          read-data: [Read0,AnotherRead0]
          write-data: [Write0,AnotherWrite0]

precice-config-file: ../precice-config.xml
```

`numRead/WriteData` will be 2.
