### ISSUE TITLE
Remove appending index from readData and writeData labels

### ISSUE THREAD

**Issue by nkr1729** [precice/calculix-adapter#18]
readData and writeData names are stored inside `PreciceInterface`.

https://github.com/precice/calculix-adapter/blob/10938d846aa99e1b5a7c8a38dbf4cf5082c586aa/adapter/PreciceInterface.h#L71

We have an array of interfaces to isolate these from getting mixed between interfaces.

https://github.com/precice/calculix-adapter/blob/10938d846aa99e1b5a7c8a38dbf4cf5082c586aa/adapter/PreciceInterface.c#L33

So from CalculiX itself, we don't need this index.
```
participants:

    ccx1:
        interfaces:
        - nodes-mesh: interface0
          patch: patch0
          read-data: [Read,AnotherRead]
          write-data: [Write,AnotherWrite]
        - nodes-mesh: interface1
          patch: patch1
          read-data: [Read,AnotherRead]
          write-data: [Write,AnotherWrite]

precice-config-file: ../precice-config.xml
```

And on the precice config side,
```
    <data:vector name="Read"  />
    <data:vector name="AnotherRead"  />
    <data:vector name="Write"  />
    <data:vector name="AnotherWrite"  />

    <mesh name="interface0">
      <use-data name="Read" />
      <use-data name="AnotherRead" />
      <use-data name="Write" />
      <use-data name="AnotherWrite" />
    </mesh>

    <mesh name="interface1">
      <use-data name="Read" />
      <use-data name="AnotherRead" />
      <use-data name="Write" />
      <use-data name="AnotherWrite" />
    </mesh>
```

Did I miss a case where we need the index to make things work?
