### ISSUE TITLE
Spil the adapter config file to one file per participant

### ISSUE THREAD

**Issue by MakisH** [precice/calculix-adapter#3]
For the OpenFOAM adapter we decided to have one adapter configuration file per participant, [as shown here](https://github.com/precice/tutorials/blob/master/CHT/heat_exchanger/buoyantSimpleFoam-CalculiX/Inner-Fluid/precice-adapter-config.yml). This was done so that we don't need to modify the solver to accept an extra command-line argument (we want to keep the solvers intact).

If there is no problem with the current setup, I propose that we also change the CalculiX adapter to look for one YAML file per participant, instead of accessing [a common file for all the participants](https://github.com/precice/tutorials/blob/master/CHT/heat_exchanger/buoyantSimpleFoam-CalculiX/config.yml). We already discussed this with @uekerman.

(as the links may break in the future, they refer to the `precice-adapter-config.yml` and `config.yml` of the heat exchanger tutorial for OpenFOAM and CalculiX)

**Comment by uekerman** [comment]
So sth like this 

```yml
participant-name: Solid
interfaces:
- nodes-mesh: Solid-Mesh
  patch: surface
  read-data: [Force]
  write-data: [Displacement]

precice-config-file: ../precice-config.xml
```
